'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Books', [
      // {
      //   title: 'The Great Gatsby',
      //   author: 'F. Scott Fitzgerald',
      //   publisher: 'Scribner',
      //   price: 150.00,
      //   stock: 10,
      //   category_id: 1,  // giả sử category_id = 1 tồn tại
      //   description: 'Classic novel set in the 1920s.',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   title: 'To Kill a Mockingbird',
      //   author: 'Harper Lee',
      //   publisher: 'J.B. Lippincott & Co.',
      //   price: 120.50,
      //   stock: 15,
      //   category_id: 2,
      //   description: 'Pulitzer Prize-winning novel about racial injustice.',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   title: '1984',
      //   author: 'George Orwell',
      //   publisher: 'Secker & Warburg',
      //   price: 130.00,
      //   stock: 20,
      //   category_id: 1,
      //   description: 'Dystopian novel about totalitarian regime.',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   title: 'The Hobbit',
      //   author: 'J.R.R. Tolkien',
      //   publisher: 'George Allen & Unwin',
      //   price: 180.00,
      //   stock: 12,
      //   category_id: 3,
      //   description: 'Fantasy adventure preceding Lord of the Rings.',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   title: 'Pride and Prejudice',
      //   author: 'Jane Austen',
      //   publisher: 'T. Egerton, Whitehall',
      //   price: 110.00,
      //   stock: 8,
      //   category_id: 2,
      //   description: 'Romantic novel exploring manners and marriage.',
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      {
        title: 'Jane Eyre',
        author: 'Charlotte Brontë',
        publisher: 'Smith, Elder & Co.',
        price: 115.00,
        stock: 9,
        category_id: 2,
        description: 'A woman\'s journey to independence and love.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Wuthering Heights',
        author: 'Emily Brontë',
        publisher: 'Thomas Cautley Newby',
        price: 110.00,
        stock: 4,
        category_id: 2,
        description: 'A dark romance set on the Yorkshire moors.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Little Women',
        author: 'Louisa May Alcott',
        publisher: 'Roberts Brothers',
        price: 100.00,
        stock: 12,
        category_id: 2,
        description: 'Coming-of-age story of four sisters growing up in America.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Sense and Sensibility',
        author: 'Jane Austen',
        publisher: 'Thomas Egerton',
        price: 105.00,
        stock: 7,
        category_id: 2,
        description: 'A tale of love, romance, and societal expectations.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Anna Karenina',
        author: 'Leo Tolstoy',
        publisher: 'The Russian Messenger',
        price: 120.00,
        stock: 5,
        category_id: 2,
        description: 'A tragic story of love and society in 19th-century Russia.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Great Expectations',
        author: 'Charles Dickens',
        publisher: 'Chapman & Hall',
        price: 110.00,
        stock: 8,
        category_id: 2,
        description: 'The growth and personal development of an orphan named Pip.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        publisher: 'Ward, Lock & Co.',
        price: 95.00,
        stock: 6,
        category_id: 2,
        description: 'A man trades his soul for eternal youth and beauty.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Dracula',
        author: 'Bram Stoker',
        publisher: 'Archibald Constable and Company',
        price: 115.00,
        stock: 5,
        category_id: 2,
        description: 'Gothic novel of love, horror, and supernatural suspense.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        publisher: 'Frederick Warne & Co.',
        price: 90.00,
        stock: 10,
        category_id: 2,
        description: 'A story of healing, friendship, and rediscovery of nature.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Tess of the d\'Urbervilles',
        author: 'Thomas Hardy',
        publisher: 'James R. Osgood, McIlvaine & Co.',
        price: 110.00,
        stock: 4,
        category_id: 2,
        description: 'A tragic tale exploring innocence, love, and societal norms.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Books', null, {});
  }
};
